### ISSUE TITLE
SyntaxError when loading component

### ISSUE THREAD

**Issue by MKM421** [yanneves/react-hero-carousel#20]
Hi, I receive an error when trying to import HeroCarousel. (screenshot and code below) Thank you!

<img width="415" alt="Screen Shot 2021-11-15 at 10 19 41 AM" src="https://user-images.githubusercontent.com/515056/141816945-e3684957-a0ef-4ecc-877b-dea87a2a9eb0.png">

```jsx
import React from 'react';
import HeroCarousel from 'react-hero-carousel';
import Button from 'components/button';
import PropTypes from 'prop-types';
import s from './HeroSlider.scss';

const HeroSlider = (props) => {

  const {
    images,
    heroText,
  } = props;

  return (
    <div className={s.heroCarousel}>
      <div className={s.heroText__Container}>
        {heroText && heroText.map(item => (
          <div key={item} className={s.heroText}>
            <h2 className={s.heroText__Title}>{item.title[0].text}</h2>
            <Button className={s.button__primary} to="">{item.cta_text}</Button>
          </div>
      ))}
      </div>
      <HeroCarousel interval={8000}>
        {images && images.map(slide => (
          <div key={slide} className={s.heroContainer} style={{ backgroundImage: `url(${slide.image.url})` }} />
      ))}
      </HeroCarousel>
    </div>
  );
};

HeroSlider.propTypes = {
  images: PropTypes.array,
  heroText: PropTypes.array,
};

export default HeroSlider;
```

**Comment by yanneves** [comment]
hey @MKM421, your code looks fine

I'd expect to see that error `Unexpected token .` when using optional chaining `obj?.property` without language support in your build, but we don't use it in this library. Does this only happen when you import `react-hero-carousel`?

Let me know if you're using create-react-app or similar to build

**Comment by yanneves** [comment]
This could also be from lack of support for [CSS Modules](https://css-tricks.com/css-modules-part-1-need/) which `react-hero-carousel` requires

**Comment by yanneves** [comment]
Determined issue occurs when missing support for [CSS Modules](https://css-tricks.com/css-modules-part-1-need/)
